language: node_js
node_js:
  - 6.4.0
branches:
  only:
    - master

script:
  - ./node_modules/.bin/bower install
  - git config credential.helper "$PWD/node_modules/.bin/git-credential-env --username=GITHUB_TOKEN"
  - git config user.name "Travis CI"
  - npm run deploy

notifications:
  email:
    on_success: never
    on_failure: always
